const vehicles = [
    { name: "10F", class: "A" },
    { name: "10F W", class: "A" },
    { name: "300R", class: "A" },
    { name: "ALBANY BWHYC", class: "A" },
    { name: "Annis Elegy RH-7", class: "A" },
    { name: "Annis Roxanne", class: "B" },
    { name: "Annis Sheavas", class: "S" },
    { name: "Autarch", class: "A" },
    { name: "Bestia GTS", class: "A" },
    { name: "Bravado Banshee S", class: "A" },
    { name: "Cheetah", class: "A" },
    { name: "Coil Eon", class: "A" },
    { name: "Comet Retro C", class: "A" },
    { name: "Comet CUP", class: "S" },
    { name: "Comet H4RxST2", class: "S" },
    { name: "Comet S2", class: "S" },
    { name: "Comet S2 Cab", class: "S" },
    { name: "Comet SR", class: "S" },
    { name: "Comet Safari", class: "S" },
    { name: "Coquette", class: "A" },
    { name: "Coquette D10", class: "A" },
    { name: "Corsita", class: "S" },
    { name: "Cyclone", class: "A" },
    { name: "Deity", class: "A" },
    { name: "Dewbauchee Champion", class: "A" },
    { name: "Dewbauchee Solace", class: "A" },
    { name: "Dominator 7cs", class: "A" },
    { name: "Dominator Jota", class: "A" },
    { name: "Dubsta 22", class: "A" },
    { name: "Dubsta 4", class: "A" },
    { name: "Dubsta 4x4", class: "A" },
    { name: "Emerus", class: "S" },
    { name: "Entity MT", class: "A" },
    { name: "Entity XXR", class: "A" },
    { name: "Enus Jubilee", class: "A" },
    { name: "Enus Paragon R", class: "A" },
    { name: "Euros", class: "A" },
    { name: "Eurosta", class: "A" },
    { name: "FMJ", class: "A" },
    { name: "Furia", class: "A" },
    { name: "Hella Phant", class: "A" },
    { name: "Ignus", class: "S" },
    { name: "Imorgon", class: "A" },
    { name: "Itali GTO", class: "A" },
    { name: "Itali RSX", class: "A" },
    { name: "Jugular", class: "A" },
    { name: "Krieger", class: "S" },
    { name: "Lynx", class: "A" },
    { name: "Monr Oec", class: "A" },
    { name: "Neon CT", class: "A" },
    { name: "OBEY RS6", class: "S" },
    { name: "Obey Argento 7", class: "A" },
    { name: "Obey Argento 7F", class: "A" },
    { name: "Obey Ten FR", class: "A" },
    { name: "Omnis e-GT", class: "A" },
    { name: "PFISTER Comet Allroad", class: "S" },
    { name: "PFISTER Comet Duke", class: "S" },
    { name: "Panthere", class: "A" },
    { name: "Pfister Comet S2R", class: "S" },
    { name: "Progen MF1 Spyder", class: "S" },
    { name: "Schlagen Coupe", class: "A" },
    { name: "Schlagen GT", class: "A" },
    { name: "Schlagen GTS", class: "A" },
    { name: "Schwartzer S", class: "A" },
    { name: "Specter C", class: "A" },
    { name: "Squalo", class: "A" },
    { name: "TEMPESTAS", class: "S" },
    { name: "Tempesta", class: "A" },
    { name: "Tempesta ES", class: "S" },
    { name: "Thrax", class: "S" },
    { name: "Turismo Cl", class: "A" },
    { name: "Tyrant", class: "S" },
    { name: "Ubermacht Sentinel G", class: "A" },
    { name: "Vacca", class: "A" },
    { name: "Virtue", class: "A" },
    { name: "Windsor", class: "A" },
    { name: "Windsor Drop", class: "A" },
    { name: "XA-21", class: "S" },
    { name: "Zorrusso", class: "S" },
    { name: "auroras", class: "S" },
    { name: "cometnor", class: "S" },
    { name: "coquette4c", class: "S" },
    { name: "cyclone ex", class: "S" },
    { name: "cypherwb", class: "A" },
    { name: "domgt420", class: "A" },
    { name: "dubmono", class: "S" },
    { name: "elegyx", class: "A" },
    { name: "gazer", class: "A" },
    { name: "gazerx", class: "A" },
    { name: "gbbisonhf", class: "A" },
    { name: "gbemerussb1", class: "S" },
    { name: "gblod4", class: "S" },
    { name: "gbprospero", class: "S" },
    { name: "gbronin", class: "S" },
    { name: "gbsapphire", class: "S" },
    { name: "gbtr3s", class: "S" },
    { name: "gstcs21", class: "S" },
    { name: "gstnex1", class: "A" },
    { name: "gstvigzx1", class: "A" },
    { name: "harmann", class: "S" },
    { name: "hycignus", class: "S" },
    { name: "hycr300", class: "A" },
    { name: "krieger Sport", class: "S" },
    { name: "la_b632021", class: "S" },
    { name: "la_bls600", class: "S" },
    { name: "la_prestige_mon", class: "S" },
    { name: "la_pt3rs", class: "S" },
    { name: "lff911gtrsr", class: "S" },
    { name: "lffchallenger", class: "A" },
    { name: "lffchargerw", class: "A" },
    { name: "lfflc500", class: "A" },
    { name: "lffm2g87", class: "A" },
    { name: "lffm3touring", class: "A" },
    { name: "lffm5cs", class: "A" },
    { name: "lfframtrx", class: "A" },
    { name: "lstalk2cs", class: "A" },
    { name: "mantis Exodus", class: "A" },
    { name: "milano", class: "S" },
    { name: "nexusrr", class: "A" },
    { name: "niobelbwk", class: "S" },
    { name: "nm_beast", class: "A" },
    { name: "obeyrs6hyc", class: "A" },
    { name: "oracxsle", class: "A" },
    { name: "pariahgt3", class: "S" },
    { name: "polycypher", class: "A" },
    { name: "polycypherwagon", class: "A" },
    { name: "polyzen", class: "S" },
    { name: "rh8widex", class: "A" },
    { name: "rhinehartm5", class: "A" },
    { name: "s790", class: "A" },
    { name: "schlc", class: "A" },
    { name: "schlagenstr", class: "S" },
    { name: "sidewinder", class: "A" },
    { name: "sunrise1", class: "A" },
    { name: "superd3", class: "S" },
    { name: "tailgaterwb", class: "A" },
    { name: "tailsr66", class: "A" },
    { name: "tenfvenm", class: "S" },
    { name: "tenflms", class: "A" },
    { name: "torero2", class: "S" },
    { name: "toros4x4", class: "A" },
    { name: "torosven", class: "A" },
    { name: "torosvenatus", class: "A" },
    { name: "vd_buffalo4h", class: "A" },
    { name: "8F Drafter", class: "B" },
    { name: "9F", class: "B" },
    { name: "9Fc", class: "B" },
    { name: "Ariant", class: "B" },
    { name: "Astron", class: "B" },
    { name: "Astron Custom", class: "B" },
    { name: "BF Club XR", class: "B" },
    { name: "Benefactor Scharman", class: "B" },
    { name: "Bravado Bison STX", class: "B" },
    { name: "Buffalo HellBound", class: "B" },
    { name: "Caracara 4x4", class: "B" },
    { name: "Caracara cara", class: "B" },
    { name: "Cheetah Cl", class: "B" },
    { name: "Cheetah Fel", class: "B" },
    { name: "Contender Baja", class: "B" },
    { name: "Cyber Hatchback", class: "B" },
    { name: "Cypher", class: "B" },
    { name: "DINKA kanjomz", class: "B" },
    { name: "Declasse Vigero ZX Convertible", class: "B" },
    { name: "Deimos Upper", class: "B" },
    { name: "Deluxo GT", class: "B" },
    { name: "Dominator GTX", class: "B" },
    { name: "Dominator TF", class: "B" },
    { name: "Drafter GPR", class: "B" },
    { name: "Draugur", class: "B" },
    { name: "Dubsta 4x4", class: "B" },
    { name: "Elegy RH8", class: "B" },
    { name: "Elegy Race", class: "B" },
    { name: "Elegy Retro C", class: "B" },
    { name: "Elegy Sedan", class: "B" },
    { name: "Faction cs", class: "B" },
    { name: "Feltzer", class: "B" },
    { name: "Feltzer Rozerino", class: "B" },
    { name: "Flash GT", class: "B" },
    { name: "Fros GTCS", class: "B" },
    { name: "GT500", class: "B" },
    { name: "Gauntlet STX", class: "B" },
    { name: "Growler", class: "B" },
    { name: "Infernus C", class: "B" },
    { name: "Issi Sport", class: "B" },
    { name: "Jester RR", class: "B" },
    { name: "Karin Mogul RS", class: "B" },
    { name: "Komoda", class: "B" },
    { name: "Lynx GPR", class: "B" },
    { name: "Mamba", class: "B" },
    { name: "Monroe", class: "B" },
    { name: "Neon", class: "B" },
    { name: "Pentro", class: "B" },
    { name: "Penumbra FF", class: "B" },
    { name: "Pfister Comet Classic", class: "B" },
    { name: "Pfister Comet S1 Tur", class: "B" },
    { name: "Raiden", class: "B" },
    { name: "Rapid GT C", class: "B" },
    { name: "Rebla GTS", class: "B" },
    { name: "Revolter", class: "B" },
    { name: "Rhinehart", class: "B" },
    { name: "Roosevelt", class: "B" },
    { name: "Roosevelt V", class: "B" },
    { name: "SX260", class: "B" },
    { name: "Schwalger Glendaleks", class: "B" },
    { name: "Sentinel SG", class: "B" },
    { name: "Specter", class: "B" },
    { name: "Speeder", class: "B" },
    { name: "Stinger", class: "B" },
    { name: "Stinger GT", class: "B" },
    { name: "Sugoi", class: "B" },
    { name: "Torero", class: "B" },
    { name: "Toros", class: "B" },
    { name: "Ty Supra", class: "B" },
    { name: "Ubermacht  Vorstand", class: "B" },
    { name: "V-STR", class: "B" },
    { name: "Vectre", class: "B" },
    { name: "Viseris", class: "B" },
    { name: "XLS", class: "B" },
    { name: "Z-Type", class: "B" },
    { name: "arbiterx", class: "B" },
    { name: "ariant BS", class: "B" },
    { name: "asteropers", class: "B" },
    { name: "cavalcade3", class: "B" },
    { name: "cypherct", class: "B" },
    { name: "domc", class: "B" },
    { name: "elegyz", class: "B" },
    { name: "f540r", class: "B" },
    { name: "gauntlets", class: "B" },
    { name: "gresleystx", class: "B" },
    { name: "gstzr3502", class: "B" },
    { name: "irisz", class: "B" },
    { name: "mojave", class: "B" },
    { name: "raidillon", class: "B" },
    { name: "razor", class: "B" },
    { name: "rrkurumacustom", class: "B" },
    { name: "rt3kvort", class: "B" },
    { name: "zlay_zr350", class: "B" },
    { name: "Übermacht Sentinel MK 4", class: "B" },
    { name: "190z", class: "C" },
    { name: "BF400", class: "C" },
    { name: "Baller LE", class: "C" },
    { name: "Baller ST", class: "C" },
    { name: "Banshee 900R", class: "C" },
    { name: "Bati 801", class: "C" },
    { name: "Bravado Buffalo EVX", class: "C" },
    { name: "Bravado Buffalo STX", class: "C" },
    { name: "Bravado Esperta", class: "C" },
    { name: "Bravado Jogger", class: "C" },
    { name: "Brawler", class: "C" },
    { name: "Buffalo Bistrol", class: "C" },
    { name: "Calico GTF", class: "C" },
    { name: "Camper", class: "C" },
    { name: "Canis Terminus", class: "C" },
    { name: "Carbon RS", class: "C" },
    { name: "Casco", class: "C" },
    { name: "Cinquemila", class: "C" },
    { name: "Contender", class: "C" },
    { name: "Coquette C", class: "C" },
    { name: "Daemon Lost", class: "C" },
    { name: "Declasse Vigero ZX", class: "C" },
    { name: "Desert Raid", class: "C" },
    { name: "Dinghy", class: "C" },
    { name: "Dominator ASP", class: "C" },
    { name: "Double-T", class: "C" },
    { name: "Esperanto Esperito", class: "C" },
    { name: "Everon", class: "C" },
    { name: "FQ 2", class: "C" },
    { name: "Gauntlet All-Road", class: "C" },
    { name: "Gauntlet Class. C", class: "C" },
    { name: "Gauntlet Hellfire", class: "C" },
    { name: "Granger", class: "C" },
    { name: "Greenwood", class: "C" },
    { name: "Gstyose Mite", class: "C" },
    { name: "Guardian", class: "C" },
    { name: "Hakuchou", class: "C" },
    { name: "Hotknife", class: "C" },
    { name: "I-Wagen", class: "C" },
    { name: "Indiana", class: "C" },
    { name: "Issi Oris", class: "C" },
    { name: "Issi Rally", class: "C" },
    { name: "Jester", class: "C" },
    { name: "Jester Class.", class: "C" },
    { name: "Jetmax", class: "C" },
    { name: "Kamacho", class: "C" },
    { name: "Landstalker XL", class: "C" },
    { name: "Longfin", class: "C" },
    { name: "Mammoth Patriot Mil-Spec", class: "C" },
    { name: "Mammoth Patriot Stretch", class: "C" },
    { name: "Marquis", class: "C" },
    { name: "MesaR", class: "C" },
    { name: "Michelli GT", class: "C" },
    { name: "Nemesis", class: "C" },
    { name: "Nightblade", class: "C" },
    { name: "Nightshade", class: "C" },
    { name: "Novak", class: "C" },
    { name: "Oraclev JD", class: "C" },
    { name: "Outlaw", class: "C" },
    { name: "PCJ 600", class: "C" },
    { name: "Peyote Gasser", class: "C" },
    { name: "Pigalle", class: "C" },
    { name: "Remus", class: "C" },
    { name: "Remust Wo", class: "C" },
    { name: "Riata", class: "C" },
    { name: "Sabre Turbo", class: "C" },
    { name: "Sabre Turbo C", class: "C" },
    { name: "SandkingSWB", class: "C" },
    { name: "SandkingXL", class: "C" },
    { name: "Savestra", class: "C" },
    { name: "Schafter V12", class: "C" },
    { name: "Scout NS", class: "C" },
    { name: "Sentinel Class.", class: "C" },
    { name: "Sentinel Class. W", class: "C" },
    { name: "Shinobi", class: "C" },
    { name: "Stallion", class: "C" },
    { name: "Streiter", class: "C" },
    { name: "Sultan Class.", class: "C" },
    { name: "Sultan RS", class: "C" },
    { name: "Sultan RS Class.", class: "C" },
    { name: "Sultan2c Sultan 2C", class: "C" },
    { name: "Suntrap", class: "C" },
    { name: "Swinger", class: "C" },
    { name: "Tahoma", class: "C" },
    { name: "Tailgater S", class: "C" },
    { name: "Tornado R", class: "C" },
    { name: "Toro", class: "C" },
    { name: "Trophy Truck", class: "C" },
    { name: "Vader", class: "C" },
    { name: "Vagrant", class: "C" },
    { name: "Vamos", class: "C" },
    { name: "Vapid Stanier LE", class: "C" },
    { name: "Wolfsbane", class: "C" },
    { name: "WooDoo Imperial", class: "C" },
    { name: "Z Bobber", class: "C" },
    { name: "Z Chopper", class: "C" },
    { name: "ZR350", class: "C" },
    { name: "Zion Class.", class: "C" },
    { name: "gresleyh", class: "C" },
    { name: "issimetro", class: "C" },
    { name: "rt3000hyc", class: "C" },
    { name: "surano", class: "C" },
    { name: "vivantgrb", class: "C" },
    { name: "windsorven", class: "C" },
    { name: "zr350pz", class: "C" },
    { name: "Admiral 1964", class: "D" },
    { name: "Akuma", class: "D" },
    { name: "Asbo", class: "D" },
    { name: "Asea", class: "D" },
    { name: "Asterope", class: "D" },
    { name: "Avarus", class: "D" },
    { name: "BMX", class: "D" },
    { name: "Bagger", class: "D" },
    { name: "Baller", class: "D" },
    { name: "Baller II", class: "D" },
    { name: "Baller LE LWB", class: "D" },
    { name: "Bearcat", class: "D" },
    { name: "Beater Dukes", class: "D" },
    { name: "BeeJay XL", class: "D" },
    { name: "Bfka", class: "D" },
    { name: "Bifta", class: "D" },
    { name: "Bison", class: "D" },
    { name: "Blade", class: "D" },
    { name: "Blazer", class: "D" },
    { name: "Blista", class: "D" },
    { name: "Blista Compact", class: "D" },
    { name: "Blista Kanjo", class: "D" },
    { name: "Bobcat XL", class: "D" },
    { name: "Bodhi", class: "D" },
    { name: "Boor", class: "D" },
    { name: "Bravado Buffalo", class: "D" },
    { name: "Bravado Buffalo S", class: "D" },
    { name: "Brioso 300", class: "D" },
    { name: "Brioso 300 W", class: "D" },
    { name: "Brioso R/A", class: "D" },
    { name: "Broadway", class: "D" },
    { name: "Brute Boxboy", class: "D" },
    { name: "Buccaneer", class: "D" },
    { name: "Buccaneer C", class: "D" },
    { name: "Burrito", class: "D" },
    { name: "Cavalcade", class: "D" },
    { name: "Cavalcade II", class: "D" },
    { name: "Cheburek", class: "D" },
    { name: "Chimera", class: "D" },
    { name: "Chino", class: "D" },
    { name: "Chino C", class: "D" },
    { name: "Cliffhanger", class: "D" },
    { name: "Clique", class: "D" },
    { name: "Clown Van", class: "D" },
    { name: "Club", class: "D" },
    { name: "Coquette BF", class: "D" },
    { name: "Cruiser", class: "D" },
    { name: "Daemon C", class: "D" },
    { name: "Declasse Alamo Unmarked", class: "D" },
    { name: "Declasse Vigero", class: "D" },
    { name: "Deviant", class: "D" },
    { name: "Diabolus", class: "D" },
    { name: "Dilettante", class: "D" },
    { name: "Dominator GTT", class: "D" },
    { name: "Drift Yosemite", class: "D" },
    { name: "Dukes", class: "D" },
    { name: "Duneloader", class: "D" },
    { name: "Dynasty", class: "D" },
    { name: "Ellie", class: "D" },
    { name: "Emperor", class: "D" },
    { name: "Endurex R Bike", class: "D" },
    { name: "Enduro", class: "D" },
    { name: "Esskey", class: "D" },
    { name: "Eudora", class: "D" },
    { name: "F620", class: "D" },
    { name: "Faction", class: "D" },
    { name: "Faction C", class: "D" },
    { name: "Fagaloa", class: "D" },
    { name: "Faggio", class: "D" },
    { name: "Faggio Mod", class: "D" },
    { name: "Faggio Sport", class: "D" },
    { name: "Fixter", class: "D" },
    { name: "Futo", class: "D" },
    { name: "Futo GTX", class: "D" },
    { name: "Gang Burrito", class: "D" },
    { name: "Gauntlet", class: "D" },
    { name: "Gauntlet Class.", class: "D" },
    { name: "Glendale", class: "D" },
    { name: "Glendale C", class: "D" },
    { name: "Grotti Brioso Fulmin", class: "D" },
    { name: "Harmann", class: "D" },
    { name: "Helikoptera", class: "D" },
    { name: "Hermes", class: "D" },
    { name: "Hexer", class: "D" },
    { name: "Hot Rod", class: "D" },
    { name: "Hustler", class: "D" },
    { name: "Impaler", class: "D" },
    { name: "Ingot", class: "D" },
    { name: "Innovation", class: "D" },
    { name: "Intruder", class: "D" },
    { name: "Issi", class: "D" },
    { name: "Issi Class.", class: "D" },
    { name: "Jackal", class: "D" },
    { name: "Journey", class: "D" },
    { name: "Journey II", class: "D" },
    { name: "Kalahari", class: "D" },
    { name: "Lost Gang Burrito", class: "D" },
    { name: "Lost Slamvan", class: "D" },
    { name: "Lurcher", class: "D" },
    { name: "Mammoth Patriot", class: "D" },
    { name: "Manana", class: "D" },
    { name: "Manana C", class: "D" },
    { name: "Manchez", class: "D" },
    { name: "Minivan", class: "D" },
    { name: "Minivan C", class: "D" },
    { name: "Moonbeam", class: "D" },
    { name: "Moonbeam C", class: "D" },
    { name: "Nebula T", class: "D" },
    { name: "Oracle", class: "D" },
    { name: "Oracle XS", class: "D" },
    { name: "Panto", class: "D" },
    { name: "Paradise", class: "D" },
    { name: "Peyote", class: "D" },
    { name: "Peyote C", class: "D" },
    { name: "Phoenix", class: "D" },
    { name: "Picador", class: "D" },
    { name: "Polyrebcu", class: "D" },
    { name: "Pony", class: "D" },
    { name: "Powersurge", class: "D" },
    { name: "Prairie", class: "D" },
    { name: "Primo", class: "D" },
    { name: "Primo C", class: "D" },
    { name: "R Tornado", class: "D" },
    { name: "Rancher XL", class: "D" },
    { name: "Rat Bike", class: "D" },
    { name: "Rat-Loader", class: "D" },
    { name: "Rat-Truck", class: "D" },
    { name: "Rebel", class: "D" },
    { name: "Regina", class: "D" },
    { name: "Retinue", class: "D" },
    { name: "Retinue MkII", class: "D" },
    { name: "Rhapsody", class: "D" },
    { name: "Rhinehart", class: "D" },
    { name: "Rumpo", class: "D" },
    { name: "Rumpo C", class: "D" },
    { name: "Rusty Emperor", class: "D" },
    { name: "Sanchez", class: "D" },
    { name: "Sanctus", class: "D" },
    { name: "Schafter", class: "D" },
    { name: "Scheisser", class: "D" },
    { name: "Scorcher", class: "D" },
    { name: "Seashark", class: "D" },
    { name: "Sentinel", class: "D" },
    { name: "Sentinel XS", class: "D" },
    { name: "Slamvan", class: "D" },
    { name: "Slamvan C", class: "D" },
    { name: "Speedo", class: "D" },
    { name: "Stanier", class: "D" },
    { name: "Stratum", class: "D" },
    { name: "Street Blazer", class: "D" },
    { name: "Sultan", class: "D" },
    { name: "Surfer", class: "D" },
    { name: "Surfer C", class: "D" },
    { name: "Swathel", class: "D" },
    { name: "Tailgater", class: "D" },
    { name: "Tampa", class: "D" },
    { name: "Tornado", class: "D" },
    { name: "Tornado 5", class: "D" },
    { name: "Tornado C", class: "D" },
    { name: "Tornado M", class: "D" },
    { name: "Tri-Cycles R Bike", class: "D" },
    { name: "Tulip", class: "D" },
    { name: "Tulip M-100", class: "D" },
    { name: "Vapid Scout Unmarked", class: "D" },
    { name: "Verus", class: "D" },
    { name: "Virgo", class: "D" },
    { name: "Virgo Class.", class: "D" },
    { name: "Virgo Class. C", class: "D" },
    { name: "Voodoo", class: "D" },
    { name: "Voodoo C", class: "D" },
    { name: "Vortex", class: "D" },
    { name: "Warrener", class: "D" },
    { name: "Warrener HKR", class: "D" },
    { name: "Washington", class: "D" },
    { name: "Weevil", class: "D" },
    { name: "Whippet R Bike", class: "D" },
    { name: "Yosemite", class: "D" },
    { name: "Yosemite R", class: "D" },
    { name: "Youga Class.", class: "D" },
    { name: "Youga Class. 4x4", class: "D" },
    { name: "Youga Cus", class: "D" },
    { name: "Zion", class: "D" },
    { name: "admiral", class: "D" },
    { name: "aleutlift", class: "D" },
    { name: "argntvnm", class: "D" },
    { name: "blackwidow", class: "D" },
    { name: "bllrmans", class: "D" },
    { name: "caracara2baja", class: "D" },
    { name: "cliquers", class: "D" },
    { name: "conada", class: "D" },
    { name: "coqvenm", class: "D" },
    { name: "cyber", class: "D" },
    { name: "cypher4x4", class: "D" },
    { name: "hades", class: "D" },
    { name: "impaler", class: "D" },
    { name: "kriegerc", class: "D" },
    { name: "lancurbn", class: "D" },
    { name: "mh6m", class: "D" },
    { name: "navarra pickup", class: "D" },
    { name: "nkbuffalos", class: "D" },
    { name: "nkbuffalosum", class: "D" },
    { name: "nkcaracara2", class: "D" },
    { name: "nkcaracara2um", class: "D" },
    { name: "nkcoquette", class: "D" },
    { name: "nkdinghy4", class: "D" },
    { name: "nkdominator3", class: "D" },
    { name: "nkgauntlet4", class: "D" },
    { name: "nkgranger2", class: "D" },
    { name: "nkgranger2um", class: "D" },
    { name: "nkomnisegt", class: "D" },
    { name: "nkomnisegtum", class: "D" },
    { name: "nkscout2020", class: "D" },
    { name: "nkscout2020um", class: "D" },
    { name: "nkshinobi", class: "D" },
    { name: "nkstanier", class: "D" },
    { name: "nkstx", class: "D" },
    { name: "nkstxum", class: "D" },
    { name: "nktorrence", class: "D" },
    { name: "para4x4", class: "D" },
    { name: "rebla4x4", class: "D" },
    { name: "reblagade", class: "D" },
    { name: "riot", class: "D" },
    { name: "Bugatti s293", class: "S" }
];
